bluejay112/robo_betty_alpha

gulpfile.js
We will add and enforce linting later.
=> Clean instead of Lint

gulpfile.js, package.json
Runs all tests within the app folder
=> Mocha Automation

README.md
=> Testing build onboarding guide

client/app/app.module.js
=> fixed routing

server/routes/form/form.controller.js, server/routes/form/index.js, server/test/ConfigureAuth.js
Small changes. Linting passes and randomized email to minimize potential concurrency issues for testing.
=> Server side refactoring

package.json, server/app.js
Added check so that server will disable auth in development mode.
=> Disable auth if dev mode.

server/test/app.js, server/test/employee.js
Added test cases for Employee server
=> Employee server test

server/routes/auth.js
Functionality for admin account to update email and password.
=> added functionality to update admin password and email

client/app/components/dashboard/sidebar/views/side-bar.html, client/app/components/dashboard/views/dashboard.html, client/assets/css/header-bar.css, client/assets/css/sidebar.css
Some fixes to Navbar
-- page not expanding
-- navbar fixed position
=> Kevin dashboard

server/routes/auth.js
Updated /signup to send `token` and `admin_id` on post
=> Updated route /auth/signup to send token and id on signup

client/app/components/dashboard/formBuilder/scripts/controllers/DeleteModalInstanceCtrl.js, client/app/components/dashboard/formBuilder/scripts/controllers/FormCreateController.js, client/app/components/dashboard/formBuilder/views/create.html, client/app/components/dashboard/formBuilder/views/deleteModal.html, client/app/components/dashboard/formBuilder/views/directive-templates/field/date.html, client/app/components/dashboard/formBuilder/views/directive-templates/field/email.html, client/app/components/dashboard/formBuilder/views/directive-templates/field/password.html, client/app/components/dashboard/formBuilder/views/directive-templates/field/textarea.html, client/app/components/dashboard/formBuilder/views/directive-templates/field/textfield.html, client/app/components/dashboard/formBuilder/views/directive-templates/form/form.html
=> Form live preview

client/app/components/dashboard/formBuilder/styles/main.css, client/app/components/dashboard/formBuilder/views/create.html, client/assets/css/form.css, client/assets/css/style.css, client/index.html
form css is improved. looks much better!
=> form css finished

client/app/app.module.js, client/app/components/dashboard/formBuilder/scripts/controllers/FormEditController.js, client/app/components/dashboard/formBuilder/views/edit.html
Added live updated and edit form integration
=> Added live updated and edit form integration

server/config/config.js, server/config/validation.js, server/routes/auth.js
(cherry picked from commit f8bc22). So that we don't get merge conflicts.
=> moved auth token to header.

client/app/shared/widget/views/header-bar.html, client/assets/css/header-bar.css
=> Kevin navbar fix

client/app/components/dashboard/formBuilder/scripts/controllers/FormCreateController.js, client/app/components/dashboard/formBuilder/views/create.html
=> moved delete confirmation to where delete button is

client/app/components/dashboard/formBuilder/scripts/controllers/DeleteModalInstanceCtrl.js, client/app/components/dashboard/formBuilder/scripts/controllers/ModalInstanceCtrl.js, client/app/components/dashboard/formBuilder/scripts/directives/field-directive.js
added all the form build stuff into its own module. This will help test.
=> all form builder stuff now in own module

server/notification/email.js, server/notification/text.js, server/routes/patientqueue/patientqueue.controller.js, server/test/notification.js
Added patient name to email and text notifications
=> Added patient name to text and email notifications

client/app/components/dashboard/patientQueue/directives/patient-queue.js, client/app/components/patientCheckin/checkin/controllers/checkin-controller.js, server/routes/employee/employee.controller.js, server/routes/employee/index.js, server/routes/patientqueue/patientqueue.controller.js, server/socket/socket.js, server/test/employee.js
This is only a test. Will be removed once confirmed email notifications are working
=> test for email notifications

client/app/components/dashboard/formBuilder/scripts/controllers/FormCreateController.js, client/app/components/dashboard/formBuilder/views/directive-templates/form/form.html, client/app/components/patientCheckin/checkin/directives/patient-form-directive.js, client/app/components/patientCheckin/checkin/services/checkin-services.js, client/test/form/FormCreateContoller.spec.js
1. Posts patient form to server & posts patient name to queue
2. displays thank you page
=> Form queue post

client/app/components/dashboard/patientQueue/directives/patient-queue.js, client/app/components/patientCheckin/checkin/controllers/checkin-controller.js, client/app/components/patientCheckin/checkin/services/checkin-services.js, client/app/components/receptionistPortal/signin/controllers/signin-controller.js, server/routes/patientqueue/patientqueue.controller.js, server/socket/socket.js
=> patient queue/sockets working

client/app/components/dashboard/employees/directives/employees.js
Added http post for adding employees
=> Fixed employee post

client/app/components/dashboard/employees/directives/employees.js, client/app/components/dashboard/employees/views/employees.html, client/assets/css/employees.css
fix employee edit number issues and make cursor: pointer when hovering over sort carets
=> Dashboard development

client/app/components/dashboard/employees/views/employees.html, client/app/components/dashboard/patientQueue/views/patients.html, client/assets/css/patient_mode.css, client/assets/css/patients.css
fixed resizing for employees/patients page on dashboard.
=> Winner winner chicken dinner
